name = "WeightedPCA"
uuid = "ee299941-4bd7-491e-86f9-95d1f98baef4"
authors = ["David Hong <dahong67@wharton.upenn.edu> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"
